### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Avantages Jeunes Connect
email: software@camarm.dev
description: Application mobile non officielle et Open Source pour la carte Avantages Jeunes !
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ajc.camarm.fr" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#b99c33'
twitter_username: ""
github_username:  camarm-dev
author: Armand Camponovo
logo: assets/images/large-logo.png
#twitter:
#  username: ''
social:
  name: Armand Camponovo
  links:
    - https://www.camarm.dev
    - https://github.com/camarm-dev

languages: ["fr"]
ampdir: amp

github: https://github.com/camarm-dev/bfc-avantagesjeunes-mobile

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
