name: Avantages Jeunes Connect
description: Votre app mobile pour utiliser pleinement votre carte Avantages Jeunes
full_description: "Avantages Jeunes Connect intègre des fonctionnalités avancées mais reste simple à utiliser pour utiliser tous le potentiel de vos avantages !<br>
<br>Découvrez les fonctionnalités suivantes :
<br>- Voir les avantages autour de vous !
<br>- Numériser votre carte; plus besoin de la sortir de votre portefeuille, présentez là au vendeur avec votre téléphone
<br>- Notez, aimez, partagez et découvrez toujours plus d'avantages !"
android: https://telegra.ph/Replace-this-link-07-23
iOS: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - image1.png
  - image2.png
  - image3.png
  - image4.png
  - image5.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://labse.camarm.fr
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
