name: Avantages Jeunes Connect
description: Votre app mobile pour utiliser pleinement votre carte Avantages Jeunes
full_description: "Avantages Jeunes Connect intègre des fonctionnalités avancées mais reste simple d'utilisation pour exploiter tout le potentiel de vos avantages !<br>
<br>Découvrez les fonctionnalités suivantes :
<br>- Voir les avantages autour de vous !
<br>- Numériser votre carte; plus besoin de la sortir de votre portefeuille, présentez là au vendeur avec votre téléphone
<br>- Notez, aimez, partagez et découvrez toujours plus d'avantages !
<br><br>Cet application non officielle est développée par un étudiant et distribuée sous la licence CECILL-2.1. Plus d'informations sur Github (en haut à droite de la page)."
android: https://telegra.ph/Replace-this-link-07-23
iOS: false
web: false
screenshots:
  - image1.jpeg
  - image2.jpeg
  - image3.jpeg
  - image4.jpeg
  - image5.jpeg
#producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://labse.camarm.fr
    image: labse.png
